---
kind: pipeline
type: exec
name: statellite

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
    - docker build -t wojiuchigua/satellite:latest .

- name: webhook
  commands:
    - curl -X POST -k https://45.207.207.163:9443/api/stacks/webhooks/76eb97b5-8da4-40ab-a8a7-20e6790fa5eb

- name: clean
  commands:
    - docker system prune -af
