version: '3.8'

services:
  drone:
    image: postgres:15.10
    container_name: postgres
    volumes:
      - /data/postgres:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=88323095.zxc
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    networks:
      - traefik
networks:
  traefik:
    external: true
