version: '3.8'

services:
  drone:
    image: wojiuchigua/qqbot:latest
    container_name: qqbot
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qqbot.entrypoints=https"
      - "traefik.http.routers.qqbot.tls=true"
      - "traefik.http.routers.qqbot.rule=Host(`qqbot.cloudyi.xyz`)"
      - "traefik.http.services.qqbot.loadbalancer.server.port=8080"
      - "traefik.http.routers.qqbot.service=qqbot"
      - "traefik.http.routers.qqbot.tls.certresolver=cyi"

    networks:
      - traefik
    restart: always

networks:
  traefik:
    external: true