version: "3"

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    command:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
      - "--api=false"
      - "--api.dashboard=false"
      - "--api.insecure=false"
      - "--api.debug=false"
      - "--ping=true"
      - "--log.level=DEBUG"
      - "--log.format=common"
      - "--accesslog=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.useBindPortIP=false"
      - "--providers.docker.network=traefik"
      - "--providers.file=true"
      - "--providers.file.watch=true"
      - "--providers.file.directory=/etc/traefik/config"
      - "--providers.file.debugloggeneratedtemplate=true"
      - "--certificatesresolvers.cyi.acme.email=cloudyunn@cloudyunn.com"
      - "--certificatesresolvers.cyi.acme.storage=acme.json"
      - "--certificatesresolvers.cyi.acme.dnschallenge=true"
      - "--certificatesresolvers.cyi.acme.dnschallenge.provider=cloudlfare"
      - "--certificatesresolvers.cyi.acme.dnschallenge.delaybeforecheck=2s"
      - "--certificatesresolvers.cyu.acme.email=cloudyunn@cloudyunn.com"
      - "--certificatesresolvers.cyu.acme.storage=acme.json"
      - "--certificatesresolvers.cyu.acme.dnschallenge=true"
      - "--certificatesresolvers.cyu.acme.dnschallenge.provider=dnspod"
      - "--certificatesresolvers.cyu.acme.dnschallenge.delaybeforecheck=2s"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # - "traefik.http.middlewares.gzip.compress=true"
      # - "traefik.http.middlewares.redir-https.redirectscheme.scheme=https"
      # - "traefik.http.middlewares.redir-https.redirectscheme.permanent=false"

      # - "traefik.http.routers.traefik-dashboard.middlewares=redir-https@docker"
      # - "traefik.http.routers.traefik-dashboard-secure.middlewares=gzip@docker"
      # - "traefik.http.routers.traefik-dashboard-api-secure.middlewares=gzip@docker"

      - "traefik.http.routers.traefik-dashboard.entrypoints=http"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`45.207.207.163`)"
      - "traefik.http.routers.traefik-dashboard.service=noop@internal"

      # - "traefik.http.routers.traefik-dashboard-secure.entrypoints=https"
      # - "traefik.http.routers.traefik-dashboard-secure.tls=true"
      # - "traefik.http.routers.traefik-dashboard-secure.rule=Host(`traefik.console.lab.io`)"
      # - "traefik.http.routers.traefik-dashboard-secure.service=noop@internal"

      # - "traefik.http.routers.traefik-dashboard-api-secure.entrypoints=http"
      # - "traefik.http.routers.traefik-dashboard-api-secure.tls=false"
      # - "traefik.http.routers.traefik-dashboard-api-secure.rule=Host(`45.207.207.163`) && PathPrefix(`/api`)"
      # - "traefik.http.routers.traefik-dashboard-api-secure.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/traefik/certs/:/certs/:ro
      - /data/traefik/config/:/etc/traefik/config/:ro
      - /data/traefik/certs/acme:/etc/traefik/acme
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider --proxy off localhost:8080/ping || exit 1"]
      interval: 3s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

    environment:
      - CF_API_EMAIL=wojiuchigua@gmail.com
      - CF_DNS_API_TOKEN=RGqKqG5kBDF7kDhS8S2jUzytz2w7wpNHYIh3zh2r
      - DNSPOD_API_KEY=f7cc8a7b37e14590a43f7e06b9326c73
networks:
  traefik:
    external: true